"""
Users route
Generated by PyNext CLI
"""
from pynext import JSONResponse, HTTPException, Request

async def get(request: Request):
    """Handle GET request."""
    return JSONResponse({
        "message": "Hello from users!",
        "method": "GET",
        "path": str(request.url.path)
    })

async def post(request: Request):
    """Handle POST request."""
    # Get request body
    body = await request.json()
    
    return JSONResponse({
        "message": "Data received",
        "method": "POST", 
        "data": body
    })

# Uncomment and implement other HTTP methods as needed:

# async def put(request: Request):
#     """Handle PUT request."""
#     pass

# async def delete(request: Request):
#     """Handle DELETE request."""
#     pass

# async def patch(request: Request):
#     """Handle PATCH request."""
#     pass
